
CREATE TABLE PROJECTLINKEDU.LOGININFO (
USERNAME varchar(30) ,
PASSWORD LONG VARCHAR,
FIRSTNAME VARCHAR (30),
LASTNAME VARCHAR (30),
EMAIL VARCHAR(50),
SECQUES VARCHAR(100),
SECANS VARCHAR(50),
USERTYPE VARCHAR(50),
CONSTRAINT USERID_PK PRIMARY KEY (USERNAME)
);

--Student detail table
create table ProjectLinkedU.StudentDetail (
  ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERNAME		VARCHAR(30),
  DOB			VARCHAR(50),
  HEIGHT		INT,
  WEIGHT		INT,
  ADDRESS		VARCHAR(500),
  CITY			VARCHAR(20),
  COUNTRY		VARCHAR(20),
  POSTALCODE		VARCHAR(20),
  PHONENO		VARCHAR(20),
  SCHOOL		VARCHAR(500),
  ENDYEAR		VARCHAR(10),
  SAT			INT,
  PSAT			INT,
  ACT			INT,
  CERTIFICATION		VARCHAR(500),
  HOBBIES		VARCHAR(500),
  ESSAY			VARCHAR(1200),
  UNIVERSITY		VARCHAR(500),
  MAJOR			VARCHAR(500),
  CONSTRAINT ID_PK PRIMARY KEY (ID),
  CONSTRAINT STUDENTID_FK FOREIGN KEY (USERNAME) REFERENCES ProjectLinkedU.LOGININFO(USERNAME)
);

--Recruiter detail table
create table ProjectLinkedU.RecruiterDetail (
  ID INTEGER not null GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERNAME		VARCHAR(30),
  UNIVERSITY	VARCHAR(100),
  DEPARTMENT	VARCHAR(100),
  PHONENO		VARCHAR(20),
  CONSTRAINT RID_PK PRIMARY KEY (ID),
  CONSTRAINT RECRUITERID_FK FOREIGN KEY (USERNAME) REFERENCES ProjectLinkedU.LOGININFO(USERNAME)
);
--default, 'jax89', 'SleepyHollow', 'Jade', 'Smith', 'jax89@gmail.com', 'Favorite Color', 'blue');

